### ISSUE TITLE
Failed to load data/model_files/extractor_stdScl_img224_inp2_out8_ep175_paper.h5

### ISSUE THREAD

**Issue by Rut-B** [jpcurbelo/human-body-reshape-DL-paper#2]
hi @jpcurbelo 
I tried to run your python photos2avatar.py code. and its try to load extractor_stdScl_img224_inp2_out8_ep175_paper.h5 model
how can I access to this file.

what is the step to get the body measurements form 2D image (front, side)

**Comment by jpcurbelo** [comment]
Hi @Rut-B. Thanks for your interest. Please, [see this issue](https://github.com/jpcurbelo/human-body-reshape-DL-paper/issues/1#issuecomment-2130517306) about the `*.h5` file.

The function `measurements_from_sil` is in charge of extracting 8 body measurements from the silhouettes images (+ gender and height), the rest are imputed to build the 3D avatar.

I hope this helps!

**Comment by jpcurbelo** [comment]
@Rut-B, any luck with this? Please, let me know to close the issue. Thanks.

**Comment by rakeshparihar** [comment]
@jpcurbelo  Its working now, thanks
