### ISSUE TITLE
Tensorflow Error on Colab

### ISSUE THREAD

**Issue by DrRaja** [jpcurbelo/human-body-reshape-DL-paper#4]
I'm trying to run this on a Google Colab with T4 GPU. However I receive this error every time I try to run it:

`tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.`

Any ideas?

**Comment by jpcurbelo** [comment]
Hi @DrRaja. Which module are you trying to run on Google Colab? I haven't tried to run the project other than on a local machine. Could you, please, provide more details?
