### ISSUE TITLE
Update Readme File Request

### ISSUE THREAD

**Issue by fvzds** [jpcurbelo/human-body-reshape-DL-paper#5]
Could you update project readme file to make the steps clear for the code to be used.
Thank you very much.

**Comment by jpcurbelo** [comment]
Hi @hesegi, thanks for your interest. We updated the Readme file with new instructions last week. Could, you, please, let me know the specific steps/parts that are still not clear? Thanks again!

**Comment by jpcurbelo** [comment]
Hi. Does this need to remain open?
