### ISSUE TITLE
Weight?

### ISSUE THREAD

**Issue by ghiu-75** [jpcurbelo/human-body-reshape-DL-paper#7]
Two more questions:
1)  For weight estimation, what should your suggestion be?
2) Can I train the program with images of (f/m) just with their height and weight info?

**Comment by jpcurbelo** [comment]
_1) For weight estimation, what should your suggestion be?_

One does not need the weight to be an input data to run the Extractor (only images and height are mandatory). Although, the weight can be useful for the imputation of the "missing" 10 measurements after the extraction of the main measurements out of the images (+ height). That is why informing the weight is recommended but not mandatory.

_2) can I train the program with images of (f/m) just with their height and weight info?_

Although the NN model (Extractor) is intended to use Images+Height (the weight is to be used during the Imputation), it could be adapted to only use Images. This is an experiment that we run in the paper, and we noticed that the accuracy (according to the metric we used) was reduced from 97% to 91%.

Hope this helps!

**Comment by ghiu-75** [comment]
Dear Jesus,I just realized that my question needs rewording.
If I want to estimate the weight of the person in photo, can your code do that?
Best Regards

    On Thursday, August 15, 2024 at 03:55:48 PM GMT+3, Jesus Perez Curbelo ***@***.***> wrote:  
 
 

   
   - For weight estimation, what should your suggestion be?

One does not need the weight to be an input data to run the Extractor (only images and height are mandatory). Although, the weight can be useful for the imputation of the "missing" 10 measurements after the extraction of the main measurements out of the images (+ height). That is why informing the weight is recommended but not mandatory.
   
   - can I train the program with images of (f/m) just with their height and weight info?

Although the NN model (Extractor) is intended to use Images+Height (the weight is to be used during the Imputation), it could be adapted to only use Images. This is an experiment that we run in the paper, and we noticed that the accuracy (according to the metric we used) was reduced from 97% to 91%.

Hope this helps!

**Comment by jpcurbelo** [comment]
In summary, in the repo you can find the code to generate the 3D avatar from two full-body images (front and side) + subject height + gender. This can be done by running `python photos2avatar.py`

The steps in the script would be:

0) The silhouettes are extracted from the images.

1) Extractor: a NN that extracts 8 measurements from the Silhouettes+Height+Gender

2) Imputer: The "missing" measurements are imputed to complete a set of 21 measurements.

3) Reshaper: Minor edits were implemented to [@zengyh1900's code](https://github.com/zengyh1900/3D-Human-Body-Shape) and it was trained by using a different set of 21 measurements. This is used to generate the 3D avatar.

The weight is to be estimated during Step 3. An imputer model is trained by using the available datasets. So, the weight is not extracted directly from the images. However, the NN (extractor) can be adapted to include the weight as a new target variable.

**Comment by ghiu-75** [comment]
Dear Jesus,
Thanks for time giving and explaining.
I understand that the weight is not estimated from the image but ;
it is found in step3 when 3d avatar is constructed using 21 measurements from where 

1) the 8 measurements obtained from image in step 1 and 2) the remaining 13 measurements from the imputer in step2 

I understand that we have to give height and gender of the images as we give images, correct?
Can code work if we do not provide height and gender?
Thanks before hand.
Ahmet Emre
    On Saturday, August 17, 2024 at 02:56:42 PM GMT+3, Jesus Perez Curbelo ***@***.***> wrote:  
 
 


In summary, in the repo you can find the code to generate the 3D avatar from two full-body images (front and side) + subject height + gender. This can be done by running python photos2avatar.py

The steps in the script would be:
   
   -    
The silhouettes are extracted form the images.

   -    
Extractor: a NN that extracts 8 measurements from the Silhouettes+Height+Gender

   -    
Imputer: The "missing" measurements are imputed to complete a set of 21 measurements.

   -    
Reshaper: Minor edits were implemented to @zengyh1900's code and it was trained by using a different set of 21 measurements. This is used to generate the 3D avatar.


The weight is to be estimated during Step 3. An imputer model is trained by using the available datasets. So, the weight is not extracted directly from the images. However, the NN (extractor) can be adapted to include the weight as a new target variable.

**Comment by jpcurbelo** [comment]
Hi, @ghiu-75. I wonder if I've missed any of your questions. Maybe this?

"Can code work if we do not provide height and gender?"

If so, please see [my comment in point 2)](https://github.com/jpcurbelo/human-body-reshape-DL-paper/issues/7#issuecomment-2291216460).

**Comment by ghiu-75** [comment]
Dear Jesus,
Thanks for your helps

I have to go remote for study. Thus won't be able to look to code before 16 Sep 2024
I am sorry.

    On Monday, August 19, 2024 at 11:28:36 PM GMT+3, Jesus Perez Curbelo ***@***.***> wrote:  
 
 


Hi, @ghiu-75. I wonder if I've missed any of your questions. Maybe this?

"Can code work if we do not provide height and gender?"

If so, please see my comment in point 2).
